#!/usr/bin/python3

import sys

from nexthop.pddf_config_parser import load_pddf_device_config
from nexthop.powercycle import log_to_kernel, powercycle


def main():
    try:
        config = load_pddf_device_config()
    except Exception as e:
        log_to_kernel(f"Failed to load PDDF configuration: {str(e)}")
        return 1

    try:
        powercycle(config)
    except Exception as e:
        log_to_kernel(f"Powercycle failed: {str(e)}")
        log_to_kernel("The control plane will reboot and leave the dataplane in an undefined state")

    return 1


if __name__ == "__main__":
    # Systemd calls this script with one of 4 arguments. "poweroff" and "halt" we don't expect.
    # A cold reboot will pass "reboot". In the first 3 cases, we continue with the powercycle.
    # Warm reboots will use kexec and will pass "kexec" as the first argument, therefore we
    # must skip the powercycle in that case.
    if len(sys.argv) > 1 and sys.argv[1] == "kexec":
        sys.exit(0)
    sys.exit(main())
