
name: Safe Upstream Sync

on:
  schedule:
    - cron: '0 3 * * *'   # Runs daily at 03:00 UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  safe-sync:
    runs-on: ubuntu-latest

    steps:
      # -----------------------
      # Checkout fork (full history)
      # -----------------------
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0       # full clone to avoid origin/ ambiguity
          ref: master

      # -----------------------
      # Setup Git & upstream
      # -----------------------
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/sonic-net/sonic-buildimage.git
          git fetch upstream master --depth=0

      # -----------------------
      # Attempt safe merge
      # -----------------------
      - name: Attempt safe merge
        id: merge
        run: |
          set -e
          SYNC_STATUS="success"
          git checkout master
          
          if git merge --no-commit --no-ff upstream/master; then
            git commit -m "Auto-sync from upstream/master"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nexthop-ai/sonic-buildimage.git master
          else
            git merge --abort
            SYNC_STATUS="conflict"
            echo "Merge conflict detected. Sync aborted."
          fi

          echo "SYNC_STATUS=$SYNC_STATUS" >> $GITHUB_ENV

      # -----------------------
      # Notify Slack after sync
      # -----------------------
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          BRANCH_NAME: master
          REPO_URL: https://github.com/nexthop-ai/sonic-buildimage
        run: |
          if [ "$SYNC_STATUS" == "success" ]; then
            STATUS_MESSAGE="✅ Auto-sync completed successfully"
          else
            STATUS_MESSAGE="⚠️ Auto-sync aborted due to merge conflicts"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "'"$STATUS_MESSAGE"'\nBranch: '"$BRANCH_NAME"'\nRepo: <'"$REPO_URL"'|View Repo>\nCommit SHA: '"$GITHUB_SHA"'"
                }
              }
            ]
          }' $SLACK_WEBHOOK_URL

